CREATE OR REPLACE TRIGGER DELETE_RESERVATION
  BEFORE DELETE ON RESERVATION
  FOR EACH ROW
BEGIN
    UPDATE TRX SET FKIdReser=null where FKIdReser= :old.IdReser;
    DELETE FROM ARRIVE WHERE FKIdReser= :old.IdReser;
    DELETE FROM DEPART WHERE FKIdReser= :old.IdReser;
    DELETE FROM DE WHERE FKIdReser= :old.IdReser;
END;